# Generated by Django 4.2.5 on 2023-10-02 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MatchingRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("place", models.CharField(max_length=100)),
                ("max_participants", models.IntegerField()),
                ("creator_phone", models.CharField(max_length=15)),
                ("is_matching", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "matching_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="matching_app.matchingroom",
                    ),
                ),
            ],
        ),
    ]
